export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Footer } from "./Footer";
export { default as Memory } from "./Memory";
export { default as Xplore } from "./Xplore";
export { default as Advertise } from "./Advertise";
export { default as Pricing } from "./Pricing";
export { default as Banner } from "./Banner";
export { default as NewsLetter } from "./NewsLetter";
